service: rs-cart-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  environment:
    PG_HOST: cart-db.cvqyz6xphj1g.us-east-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: cart-db
    PG_USERNAME: postgress
    PG_PASSWORD: pcCmKfeKUQp7afJSM2sk


functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
